name: Service Desk Local
values:
  - key: base_url
    value: 'http://localhost'
    enabled: true
  - key: api_base_url
    value: '{{base_url}}/api'
    enabled: true
  - key: token
    value: ''
    enabled: true
  - key: ticket_id
    value: '1'
    enabled: true
  - key: category_id
    value: '1'
    enabled: true
  - key: comment_id
    value: '1'
    enabled: true
  - key: user_id
    value: '1'
    enabled: true
color: 0
